const express=require('express')
const authController=require('../controllers/auth')
const validator=require('../middleware/validators')

const router=express.Router()
router.get('/login',authController.getLogin)
router.post('/login',[validator.validateLogin,authController.postLogin])
router.post('/logout',authController.postLogout)
router.get('/signup',[authController.getSignup])
router.post('/signup',[validator.validateSignUp,authController.postSignup])
router.get('/reset',authController.getResetPassword)
router.post('/reset',[validator.validateReset,authController.postResetPassword])
router.get('/reset/:token',authController.getNewPassword)
router.post('/new-password',[validator.validateNewPassword,authController.postNewPassword])
module.exports=router;